"""Remove is_internal from Devices model

Revision ID: 22d404b81d15
Revises: 6fb434a74147
Create Date: 2024-08-04 15:55:04.110683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d404b81d15'
down_revision = '6fb434a74147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
