"""Add is_internal, ports, services to Devices model

Revision ID: 6fb434a74147
Revises: ba38a8053db5
Create Date: 2024-08-04 15:52:50.069632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb434a74147'
down_revision = 'ba38a8053db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('open_ports', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('services', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('services')
        batch_op.drop_column('open_ports')
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###
